# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/core/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/core

PRODUCT_COPY_FILES += \
    vendor/xiaomi/core/proprietary/system/bin/shelld:$(TARGET_COPY_OUT_SYSTEM)/bin/shelld \
    vendor/xiaomi/core/proprietary/system/etc/permissions/MiuiSettingsSearchLib.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/MiuiSettingsSearchLib.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/android-support-v13.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android-support-v13.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/cloud-common.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cloud-common.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/com.miui.core.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.miui.core.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/com.miui.rom.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.miui.rom.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/com.miui.system.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.miui.system.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/com.qti.slalib.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.qti.slalib.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/gson.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/gson.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/micloud-sdk.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/micloud-sdk.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/miui-push.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/miui-push.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/miui-stat.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/miui-stat.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/privapp-com.miui.core.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-com.miui.core.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/protobuf.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/protobuf.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/permissions/security-device-credential-sdk.jar.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/security-device-credential-sdk.jar.xml \
    vendor/xiaomi/core/proprietary/system/etc/sysconfig/config-com.miui.core.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.miui.core.xml \
    vendor/xiaomi/core/proprietary/system/etc/sysconfig/config-com.miui.rom.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.miui.rom.xml \
    vendor/xiaomi/core/proprietary/system/etc/sysconfig/config-com.miui.system.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.miui.system.xml \
    vendor/xiaomi/core/proprietary/system/etc/sysconfig/config-com.xiaomi.micloud.sdk.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/config-com.xiaomi.micloud.sdk.xml \
    vendor/xiaomi/core/proprietary/system/lib/libexmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexmedia.so \
    vendor/xiaomi/core/proprietary/system/lib/libimage_arcsoft_4plus.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimage_arcsoft_4plus.so \
    vendor/xiaomi/core/proprietary/system/lib/libmiui_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiui_runtime.so \
    vendor/xiaomi/core/proprietary/system/lib/libmiuiblur.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiuiblur.so \
    vendor/xiaomi/core/proprietary/system/lib/libmiuidiffpatcher.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiuidiffpatcher.so \
    vendor/xiaomi/core/proprietary/system/lib/libmiuinative.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiuinative.so \
    vendor/xiaomi/core/proprietary/system/lib/libmiuixlog.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiuixlog.so \
    vendor/xiaomi/core/proprietary/system/lib/libmp3lame.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmp3lame.so \
    vendor/xiaomi/core/proprietary/system/lib/libsechook.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsechook.so \
    vendor/xiaomi/core/proprietary/system/lib/libshell.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshell.so \
    vendor/xiaomi/core/proprietary/system/lib/libshell_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshell_jni.so \
    vendor/xiaomi/core/proprietary/system/lib/libshellservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshellservice.so \
    vendor/xiaomi/core/proprietary/system/lib/libstlport_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstlport_shared.so \
    vendor/xiaomi/core/proprietary/system/lib/libthemeutils_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libthemeutils_jni.so \
    vendor/xiaomi/core/proprietary/system/lib/libxlog.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libxlog.so \
    vendor/xiaomi/core/proprietary/system/lib64/libexmedia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libexmedia.so \
    vendor/xiaomi/core/proprietary/system/lib64/libimage_arcsoft_4plus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimage_arcsoft_4plus.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmiui_runtime.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmiui_runtime.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmiuiblur.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmiuiblur.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmiuidiffpatcher.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmiuidiffpatcher.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmiuinative.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmiuinative.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmiuixlog.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmiuixlog.so \
    vendor/xiaomi/core/proprietary/system/lib64/libmp3lame.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmp3lame.so \
    vendor/xiaomi/core/proprietary/system/lib64/libsechook.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsechook.so \
    vendor/xiaomi/core/proprietary/system/lib64/libshell.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libshell.so \
    vendor/xiaomi/core/proprietary/system/lib64/libshell_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libshell_jni.so \
    vendor/xiaomi/core/proprietary/system/lib64/libshellservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libshellservice.so \
    vendor/xiaomi/core/proprietary/system/lib64/libstlport_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstlport_shared.so \
    vendor/xiaomi/core/proprietary/system/lib64/libthemeutils_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libthemeutils_jni.so \
    vendor/xiaomi/core/proprietary/system/lib64/libxlog.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libxlog.so \
    vendor/xiaomi/core/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/xiaomi/core/proprietary/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    vendor/xiaomi/core/proprietary/vendor/lib/libcdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcdsprpc.so \
    vendor/xiaomi/core/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    vendor/xiaomi/core/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/xiaomi/core/proprietary/vendor/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so \
    vendor/xiaomi/core/proprietary/vendor/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so \
    vendor/xiaomi/core/proprietary/vendor/lib64/libcdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcdsprpc.so \
    vendor/xiaomi/core/proprietary/vendor/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so \
    vendor/xiaomi/core/proprietary/vendor/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so

PRODUCT_PACKAGES += \
    miuisystem \
    RtMiCloudSDK \
    miui \
    MiuiBooster \
    MiuiSettingsSearchLib \
    android-support-v13 \
    android-support-v7-recyclerview \
    cloud-common-runtime \
    com.qti.slalib \
    framework-ext-res \
    gson \
    miuipushsdkshared \
    miuistatssdkshared \
    protobuf \
    security-device-credential-sdk
